### ISSUE TITLE
Website links still need to be recalibrated

### ISSUE THREAD

**Issue by rpaladin** [armory3d/armory_web#19]
Mentioned earlier in #15 - Bump requested by another user:

![image](https://user-images.githubusercontent.com/69180012/168404366-a04b2705-9c68-4d47-b40d-864c0412cabc.png)

<hr  />

@luboslenco, new navbar links; and even some old navbar links, still do not show up in search engine results.

![image](https://user-images.githubusercontent.com/69180012/168404269-62dfec4c-4faf-4e3e-8270-e8523c3d3c16.png)

 This can be solved by requesting a `recawl` from Google: https://developers.google.com/search/docs/advanced/crawling/ask-google-to-recrawl

**Comment by luboslenco** [comment]
Recrawl has been requested, not sure how long it usually takes but should get recrawled eventually.

**Comment by rpaladin** [comment]
Hi, sorry to bump. Any new developments relating to this issue? For some reason, the website still shows the old website URLs, even before the last PR (site migration).

Perhaps we need to add a _**sitemap**_?
