### ISSUE TITLE
Direct link to release notes for specific version

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armory_web#21]
Hi, as briefly mentioned in https://github.com/armory3d/armory_web/pull/6#issuecomment-933011351 it would be great to be able to directly link to a specific release in the release notes by appending an ID to the URL. Then older links to the release notes could still point to the corresponding release they regard.

Since all releases are in one big html document, I guess all that has to be done is to add a small script that changes what release is shown based on an ID/anchor in the URL.

**Comment by rpaladin** [comment]
I'll try to implement `id` attributes to all of the monthly titles in the future.
