### ISSUE TITLE
Armory API documentation down?

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory_web#4]
the API documentation currently returns a 404
File not found
[https://armory3d.org/manual/api/ ](https://armory3d.org/manual/api/ )

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armory_web/commit/34a8b5e04d05f349608cbb5c28ad8524a044539f, updated link in wiki to https://armory3d.org/api. Thanks for report.
